/*

 TEST.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 100 x 100
   Tile set      : C:\genesis\tools\gbtd\TEST.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define testWidth 100
#define testHeight 100
#define testBank 0

extern unsigned char test[];

/* End of TEST.H */
